package com.shvarsman.menuplanner.domain.model

enum class Category(val displayName: String) {
    FRUITS("Фрукты"),
    BERRIES("Ягоды"),
    CITRUS("Цитрусовые"),
    VEGETABLES("Овощи"),
    HERBS("Зелень и травы"),
    MUSHROOMS("Грибы"),
    MEAT("Мясо"),
    POULTRY("Птица"),
    OFFAL("Субпродукты"),
    FISH("Рыба"),
    SEAFOOD("Морепродукты"),
    CANNED("Консервы"),
    DAIRY("Молочная продукция"),
    CHEESE("Сыры"),
    EGGS("Яйца"),
    BREAD_BAKING("Хлеб и выпечка"),
    GROCERY("Бакалея"),
    SAUCES("Соусы"),
    GRAINS("Крупы"),
    LEGUMES("Бобовые"),
    PASTA("Макароны"),
    SPICES("Специи"),
    NUTS_SEEDS("Орехи и семена"),
    DRIED_FRUITS("Сухофрукты"),
    FROZEN("Заморозка"),
    COFFEE_TEA("Кофе и чай"),
    DRINKS_NON_ALCOHOL("Напитки безалкогольные"),
    DRINKS_ALCOHOL("Напитки алкогольные"),
    HONEY_SWEETS("Мёд и сладости"),
    SNACKS("Снеки")
}
