package com.shvarsman.menuplanner.domain.model

enum class CookingMethod(val displayName: String) {
    BOILING_STOVETOP("Варка (на плите)"),
    STEAMING("Варка на пару"),
    POACHING("Припускание"),
    PAN_FRYING("Жарка основная (сковорода)"),
    DEEP_FRYING("Жарка во фритюре"),
    SAUTEING("Пассерование"),
    STEWING("Тушение"),
    OVEN_BAKING("Запекание в духовке"),
    BAKING_IN_POTS("Запекание в горшочках"),
    BAKING_IN_FOIL_SLEEVE("Запекание в фольге / рукаве"),
    GRATINATING("Гратинирование"),
    GRILLING("Гриль"),
    BARBECUE_OPEN_FIRE("Барбекю / Мангал / Открытый огонь"),
    HOT_SMOKING("Копчение горячее"),
    COLD_SMOKING("Копчение холодное"),
    SIMMERING_LOW("Томление"),
    CONFIT("Конфи"),
    SOUS_VIDE("Су-вид (Sous vide)"),
    BLANCHING("Бланширование"),
    FLAMBEING("Фламбирование"),
    MICROWAVE_COOKING("Приготовление в микроволновой печи (СВЧ)"),
    REHEATING_DEFROSTING("Разогрев / Разморозка"),
    STOVE_GENERAL("Плита (общее)"),
    GAS_STOVE("Газовая плита"),
    INDUCTION_STOVE("Индукционная плита"),
    ELECTRIC_STOVE("Электрическая плита"),
    OVEN("Духовой шкаф (духовка)"),
    CONVECTION_OVEN("Конвекционная духовка"),
    AIR_FRYER("Аэрогриль"),
    MICROWAVE_OVEN("Микроволновка (СВЧ)"),
    SLOW_COOKER("Мультиварка"),
    PRESSURE_MULTICOOKER("Мультиварка-скороварка"),
    PRESSURE_COOKER_CLASSIC("Скороварка (классическая)"),
    ELECTRIC_STEAMER("Пароварка (электрическая)"),
    FRYING_PAN("Сковорода (обычная, антипригарная, чугунная)"),
    GRILL_PAN("Сковорода-гриль"),
    WOK("Вок"),
    SAUTE_PAN("Сотейник"),
    POT("Кастрюля"),
    CERAMIC_POTS("Горшочки керамические"),
    MANTOVARKA_STEAMER("Мантоварка"),
    DEEP_FRYER("Фритюрница"),
    ELECTRIC_GRILL("Электрогриль"),
    BRAZIER_SKEWERS("Мангал / Решётка / Шампуры"),
    SMOKEHOUSE("Коптильня"),
    SOUS_VIDE_MACHINE("Су-вид машина (погружной циркулятор)"),
    GAS_TORCH("Газовая горелка (для фламбирования)"),
    WAFFLE_MAKER("Вафельница"),
    TOASTER("Тостер"),
    MINI_OVEN_ROASTER("Ростер / Мини-печь"),
    HEATED_BLENDER_SOUP_MAKER("Блендер с нагревом (суповарка)"),
    BREAD_MAKER("Хлебопечка"),
    YOGURT_MAKER("Йогуртница"),
    NO_COOKING_ASSEMBLY("Без приготовления (сборка, нарезка)"),
    COLD_MARINATING("Маринование (холодное)"),
    SALTING("Соление"),
    FERMENTATION("Ферментация / Квашение"),
    VINEGAR_PICKLING("Маринование с уксусом (консервация холодная)"),
    CURING_DRYING("Вяление / Сушка"),
    FREEZING("Заморозка"),
    WHIPPING_AERATION("Взбивание / Аэрация"),
    INFUSING("Настаивание")
}